[package]
name = "util-derive"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
check_keyword = "0.4.1"
convert_case = "0.10.0"
darling = "0.23.0"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "2.0.114", features = ["full"] }
